on:
  schedule:
    - cron: "*/15 * * * *"

name: fetch-data-wfs

jobs:
  fetch-data-from-wfs:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: install linux libraries
        run: |
          sudo apt install libsodium-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgdal-dev libproj-dev
          sudo apt install libudunits2-dev

      - name: Install packages
        run: |
          source("src/install_packages.R")
        shell: Rscript {0}

      - name: Read data from WFS
        run: |
          source("src/read_data_from_wfs.R")
        shell: Rscript {0}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Fetch data"
          target_branch: automatic-update
          add_timestamp: true

      - name: get branch name
        run: |
          git branch --show-current

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          target_branch: main
          title: "[AUTO] Update data"
          template: .github/PULL_REQUEST_TEMPLATE.md
          reviewer: ${{ github.actor }}
          label: automated workflow
          get_diff: false
          ignore_users: "dependabot"

