on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [main]
  workflow_dispatch:
    branches: [ main ]

name: fetch-data

jobs:
  fetch-data-webdav:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release'}

    env:
      WEBDAV_PASSWORD: ${{ secrets.WEBDAV_SECRET_VMM_RATTENAPP }}
      GITHUB_TOKEN: ${{ secrets.WORKFLOWS }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOWS }}

      - name: fetch-data-via-webdav
        run: .\\src\\download_via_webdav.bat ${{ secrets.WEBDAV_PASSWORD }}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.WORKFLOWS }}
          commit_prefix: "[AUTO]"
          commit_message: "Fetch data"
          target_branch: automatic-update
          add_timestamp: true

      - name: get branch name
        run: |
          git branch --show-current
